language: rust
# 2020-06-17 - nightly hasn't had rustfmt since 2020-06-10, so builds fail on
# that toolchain. We want to use it as far as is possible, though.
rust:
    - nightly-2020-06-10

cache: cargo

install:
    - rustup component add clippy rustfmt
    - cargo install cargo-udeps
    - cargo build

script:
    - tools/checks
