language: rust
rust:
    - nightly-2020-06-10

cache: cargo

install:
    - rustup component add clippy rustfmt
    - cargo install cargo-udeps
    - cargo build

script:
    - cargo build
    - cargo test
    - cargo fmt -- --check
    - cargo clippy -- --deny warnings
    - cargo udeps --locked --all-targets
