language: rust
# 2020-06-17 - nightly hasn't had rustfmt since 2020-06-10, so builds fail on
# that toolchain. We want to use it as far as is possible, though.
rust:
    - nightly
    - nightly-2020-06-10

jobs:
    allow_failures:
        - rust: nightly

cache: cargo

install:
    - rustup component add clippy rustfmt
    - cargo install cargo-udeps
    - cargo build

# dup of the list in .git-hooks/pre-commit
script:
    - cargo build --locked
    - cargo test
    - cargo fmt -- --check
    - cargo clippy -- --deny warnings
    - cargo udeps --locked --all-targets
