language: rust
rust:
    - nightly

cache: cargo

install:
    - rustup component add clippy
    - cargo install cargo-udeps
    - cargo build

script:
    - cargo build
    - cargo test
    - cargo clippy -- --deny warnings
    - cargo udeps --locked --all-targets
